name: mumet
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.2
  stacked: ^2.3.15
  flutter_svg: ^1.0.3
  stacked_hooks: ^0.2.1+1
  firebase_core: ^1.13.1
  flutter_spinkit: ^5.1.0
  stacked_themes: ^0.3.8+1
  stacked_services: ^0.9.5
  stacked_firebase_auth: ^0.2.10+2
  google_fonts: ^3.0.1
  flex_color_scheme: ^5.1.0
  introduction_screen: ^3.0.0
  syncfusion_flutter_gauges: ^20.2.45
  syncfusion_flutter_charts: ^20.2.45
  grouped_list: ^5.1.1
  flutter_form_builder: ^7.3.0
  form_builder_validators: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.7
  stacked_generator: ^0.7.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
