// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAEpWNC8pGx7YLz11QuLr_av6B1DuJX2w',
    appId: '1:653167774186:web:fd59b167ea02378ef1ca93',
    messagingSenderId: '653167774186',
    projectId: 'pro-2048-game',
    authDomain: 'pro-2048-game.firebaseapp.com',
    databaseURL: 'https://pro-2048-game.firebaseio.com',
    storageBucket: 'pro-2048-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz4GD_IueoE0DJqt_expf1DuxVfN9hyCA',
    appId: '1:653167774186:android:8dc6a7d426b40544f1ca93',
    messagingSenderId: '653167774186',
    projectId: 'pro-2048-game',
    databaseURL: 'https://pro-2048-game.firebaseio.com',
    storageBucket: 'pro-2048-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvr-9z5qe1ufwVnx9XFmS2fYrkjlrwtKc',
    appId: '1:653167774186:ios:de7570276ba4dfd0f1ca93',
    messagingSenderId: '653167774186',
    projectId: 'pro-2048-game',
    databaseURL: 'https://pro-2048-game.firebaseio.com',
    storageBucket: 'pro-2048-game.appspot.com',
    iosClientId: '653167774186-trn5htqsi11v5gu55f7gqsbqicnei1ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.mumet',
  );
}
